package LangApp2.ExamplePack;

import LangApp2.GUI.ExcerciseGUIIf;
import LangApp2.Test.ExcerciseIf;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Lach on 2017-04-14.
 */
public class StringExcerciseExampleGUI implements ExcerciseGUIIf {
    private JTextField textField1;
    private JPanel mainGUIPanel;
    private JLabel label1;

    private ExcerciseIf content;

    public JPanel GetJPanel() {
        return mainGUIPanel;
    }

    @Override
    public ExcerciseIf GetExcercise() {
        return content;
    }

    @Override
    public void SetExcercise(ExcerciseIf exc) {
        content = exc;
        label1.setText(content.GetName());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainGUIPanel = new JPanel();
        mainGUIPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        label1 = new JLabel();
        label1.setText("Label");
        mainGUIPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textField1 = new JTextField();
        mainGUIPanel.add(textField1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainGUIPanel;
    }
}
